apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awesome-cats-cert
  namespace: default
spec:
  secretName: awesome-cats-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: devops-aitbubu.tech
  dnsNames:
  - devops-aitbubu.tech
