apiVersion: v1
kind: Secret
metadata:
  name: SECRET_NAME
type: Opaque
data:
  host: BASE64_ENCODED_HOST
  username: BASE64_ENCODED_USERNAME
  password: BASE64_ENCODED_PASSWORD
  dbname: BASE64_ENCODED_DBNAME


